starting work on release abandon

diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -1095,3 +1095,355 @@ r,[no]remote     Delete remote branch
 	echo "- You are now on branch '$(git_current_branch)'"
 	echo
 }
+	echo
+}
+
+cmd_abandon() {
+	OPTIONS_SPEC="\
+git flow release abandon [-h] [-F] [-s] [-u] [-m | -f] [-p] [-k] [-n] [-b] [-S] <version>
+
+
+Abandon a release branch
+--
+h,help              Show this help
+showcommands!       Show git commands while executing them
+F,[no]fetch         Fetch from origin before performing finish
+s,sign!             Sign the release tag cryptographically
+u,signingkey!       Use the given GPG-key for the digital signature (implies -s)
+m,message!          Use the given tag message
+f,[no]messagefile=  Use the contents of the given file as a tag message
+p,[no]push          Push to origin after performing finish
+[no]pushdevelop     Push the develop branch
+k,[no]keep          Keep branch after performing finish
+[no]keepremote      Keep the remote branch
+[no]keeplocal       Keep the local branch
+D,[no]force_delete  Force delete release branch after finish
+b,[no]nobackmerge   Don't back-merge master, or tag if applicable, in develop
+S,[no]squash        Squash release during merge
+[no]ff-master       Fast forward master branch if possible
+nodevelopmerge!  Don't back-merge develop branch
+"
+	# Define flags
+	DEFINE_boolean 'fetch' false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean 'sign' false "sign the release tag cryptographically" s
+	DEFINE_string  'signingkey' "" "use the given GPG-key for the digital signature (implies -s)" u
+	DEFINE_string  'message' "" "use the given tag message" m
+	DEFINE_string  'messagefile' "" "use the contents of the given file as a tag message" f
+	DEFINE_boolean 'push' false "push to $ORIGIN after performing finish" p
+	DEFINE_boolean 'pushdevelop' false "push the develop branch"
+	DEFINE_boolean 'keep' false "keep branch after performing finish" k
+	DEFINE_boolean 'keepremote' false "keep the remote branch"
+	DEFINE_boolean 'keeplocal' false "keep the local branch"
+	DEFINE_boolean 'force_delete' false "force delete release branch after finish" D
+	DEFINE_boolean 'nobackmerge' false "don't back-merge $MASTER_BRANCH, or tag if applicable, in $DEVELOP_BRANCH " b
+	DEFINE_boolean 'squash' false "squash release during merge" S
+	DEFINE_boolean 'squash-info' false "add branch info during squash"
+	DEFINE_boolean 'ff-master' false "fast forward master branch if possible"
+	DEFINE_boolean 'nodevelopmerge' false "don't merge $BRANCH into $DEVELOP_BRANCH "
+
+	# Override defaults with values from config
+	gitflow_override_flag_boolean   "release.abandon.fetch"          "fetch"
+	gitflow_override_flag_boolean   "release.abandon.sign"           "sign"
+	gitflow_override_flag_boolean   "release.abandon.push"           "push"
+	gitflow_override_flag_boolean   "release.abandon.pushdevelop"    "pushdevelop"
+	gitflow_override_flag_boolean   "release.abandon.keep"           "keep"
+	gitflow_override_flag_boolean   "release.abandon.keepremote"     "keepremote"
+	gitflow_override_flag_boolean   "release.abandon.keeplocal"      "keeplocal"
+	gitflow_override_flag_boolean   "release.abandon.force-delete"   "force_delete"
+	gitflow_override_flag_boolean   "release.abandon.nobackmerge"    "nobackmerge"
+	gitflow_override_flag_boolean   "release.abandon.squash"         "squash"
+	gitflow_override_flag_boolean   "release.abandon.squash-info"    "squash_info"
+	gitflow_override_flag_boolean   "release.abandon.ff-master"      "ff-master"
+	gitflow_override_flag_string    "release.abandon.signingkey"     "signingkey"
+	gitflow_override_flag_string    "release.abandon.message"        "message"
+	gitflow_override_flag_string    "release.abandon.messagefile"    "messagefile"
+	gitflow_override_flag_boolean   "release.abandon.nodevelopmerge" "nodevelopmerge"
+
+	# Parse arguments
+	parse_args "$@"
+
+	# Use current branch if no version is given
+	if [ "$VERSION" = "" ]; then
+		gitflow_use_current_branch_version
+	fi
+
+
+	# Run filter on the version
+	VERSION=$(run_filter_hook release-finish-version $VERSION)
+	if [ $? -eq 127 ]; then
+		die $VERSION
+	fi
+
+	# Use branch name if no tag name is given
+	if [ "$FLAGS_tagname" != "" ]; then
+		TAGNAME=$FLAGS_tagname
+	else
+		TAGNAME=$VERSION
+	fi
+
+	# As VERSION might have changed reset BRANCH with new VERSION
+	BRANCH=$PREFIX$VERSION
+
+	BASE_BRANCH=$(gitflow_config_get_base_branch $BRANCH)
+	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
+	git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't finish the release branch '$BRANCH'."
+
+	# Handle flags that imply other flags
+	if [ "$FLAGS_signingkey" != "" ]; then
+		FLAGS_sign=$FLAGS_TRUE
+	fi
+
+	# Keeping both branches implies the --keep flag to be true.
+	if flag keepremote && flag keeplocal; then
+		FLAGS_keep=$FLAGS_TRUE
+	fi
+
+	# Pushing implies we push all.
+	if flag push; then
+		FLAGS_pushdevelop=$FLAGS_TRUE
+	fi
+	# If we push either of these it means we need to do a push
+	if flag pushdevelop; then
+		FLAGS_push=$FLAGS_TRUE
+	fi
+
+	# Sanity checks
+	require_branch "$BRANCH"
+	require_clean_working_tree
+
+	# We always fetch the Branch from Origin
+	# This is done to avoid possible commits on the remote that are not
+	# merged into the local branch
+	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+			git_fetch_branch "$ORIGIN" "$BRANCH"
+	fi
+
+	if [ "$BASE_BRANCH" = "$DEVELOP_BRANCH" ]; then
+		_abandon_from_develop
+	else
+		_abandon_base
+	fi
+}
+
+#
+# Function used by abandon command to abandon the release branch
+# Called when the base of the release is the $DEVELOP_BRANCH
+#
+_abandon_from_develop() {
+	local opts merge_branch commit keepmsg remotebranchdeleted localbranchdeleted compare_refs_result merge_result
+
+	remotebranchdeleted=$FLAGS_FALSE
+	localbranchdeleted=$FLAGS_FALSE
+
+	# Update local branches with remote branches
+	if flag fetch; then
+		git_fetch_branch "$ORIGIN" "$DEVELOP_BRANCH"
+	fi
+
+	# Check if the local branches have all the commits from the remote branches
+	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
+	fi
+	if git_remote_branch_exists "$ORIGIN/$DEVELOP_BRANCH"; then
+		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+	fi
+
+	# Try to merge into develop unless 'nodevelopmerge' has been specified.
+	# In case a previous attempt to finish this release branch has failed,
+	# but the merge into develop was successful, we skip it now
+	if noflag nodevelopmerge; then
+		if ! git_is_branch_merged_into "$merge_branch" "$DEVELOP_BRANCH"; then
+			git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+
+			if noflag nobackmerge; then
+				git_do merge --no-ff "$commit" || die "There were merge conflicts." # TODO: What do we do now?
+			else
+				commit="$BRANCH"
+				if noflag squash; then
+					git_do merge --no-ff "$commit" || die "There were merge conflicts." # TODO: What do we do now?
+				else
+					git_do merge --squash "$commit" || die "There were merge conflicts." # TODO: What do we do now?
+					flag squash_info && gitflow_create_squash_message "Merged release branch '$BRANCH'" "$DEVELOP_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
+					git_do commit
+				fi
+			fi
+		fi
+	fi
+
+	# Delete branch
+	if noflag keep; then
+
+		# Always delete remote first
+		if noflag keepremote;then
+			if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+				git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
+			fi
+		fi
+
+		# Delete local after remote to avoid warnings
+		if noflag keeplocal; then
+			if flag force_delete; then
+				git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+			else
+				if noflag squash; then
+					git_do branch -d "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+				else
+					git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+				fi
+			fi
+		fi
+
+		# no more branches: we can safely remove config section
+		if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
+			gitflow_config_remove_base_section "$BRANCH"
+		fi
+	fi
+
+	if flag push; then
+		if flag pushdevelop; then
+			git_do push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
+		fi
+		if noflag notag && flag pushtag; then
+			git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
+		fi
+	fi
+
+	echo
+	echo "Summary of actions:"
+	if flag fetch; then
+		echo "- Latest objects have been fetched from '$ORIGIN'"
+	fi
+	[ "$commit" = "$BRANCH" ] && echo "- Release branch '$BRANCH' has been merged into '$DEVELOP_BRANCH'"
+
+	if noflag keep; then
+		if [ $localbranchdeleted -eq $FLAGS_TRUE ]; then
+			keepmsg="has been locally deleted"
+		else
+			keepmsg="is still locally available"
+		fi
+		if [ $remotebranchdeleted -eq $FLAGS_TRUE ]; then
+			keepmsg=$keepmsg"; it has been remotely deleted from '$ORIGIN'"
+		elif git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+			keepmsg=$keepmsg"; it is still remotely available on '$ORIGIN'"
+		fi
+	else
+		keepmsg="is still locally available"
+		if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+			keepmsg=$keepmsg"; it is still remotely available on '$ORIGIN'"
+		fi
+	fi
+	echo "- Release branch '$BRANCH' "$keepmsg
+
+	if flag push; then
+		echo "- '$DEVELOP_BRANCH' has been pushed to '$ORIGIN'"
+	fi
+	echo "- You are now on branch '$(git_current_branch)'"
+	echo
+}
+
+#
+# Function used by finish command to actually finish the release branch
+# Called when the base of the release is NOT the $DEVELOP_BRANCH
+#
+
+_abandon_base() {
+	local opts merge_branch commit keepmsg localbranchdeleted remotebranchdeleted
+
+	remotebranchdeleted=$FLAGS_FALSE
+	localbranchdeleted=$FLAGS_FALSE
+
+	# Update local branches with remote branches
+	if flag fetch; then
+		git_fetch_branch "$ORIGIN" "$BASE_BRANCH"
+	fi
+
+	# Check if the local branches have all the commits from the remote branches
+	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
+	fi
+	if git_remote_branch_exists "$ORIGIN/$BASE_BRANCH"; then
+		require_branches_equal "$BASE_BRANCH" "$ORIGIN/$BASE_BRANCH"
+	fi
+
+	# Try to merge into base branch.
+	# In case a previous attempt to finish this release branch has failed,
+	# but the merge into develop was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH"; then
+		git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
+		if noflag squash; then
+			git_do merge --no-ff "$BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
+		else
+			git_do merge --squash "$BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
+			flag squash_info && gitflow_create_squash_message "Merged release branch '$BRANCH'" "$BASE_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
+			git_do commit
+		fi
+	fi
+
+	# Delete branch
+	if noflag keep; then
+
+		# Always delete remote first
+		if noflag keepremote;then
+			if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+				git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
+			fi
+		fi
+
+		# Delete local after remote to avoid warnings
+		if noflag keeplocal; then
+			if [ "$BRANCH" = "$(git_current_branch)" ]; then
+				git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
+			fi
+			if flag force_delete; then
+				git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+			else
+				git_do branch -d "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+			fi
+		fi
+
+		# no more branches: we can safely remove config section
+		if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
+			gitflow_config_remove_base_section "$BRANCH"
+		fi
+	fi
+
+	if flag push; then
+		if flag pushdevelop; then
+			git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
+		fi
+		if noflag notag && flag pushtag; then
+			git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
+		fi
+	fi
+
+	echo
+	echo "Summary of actions:"
+	if flag fetch; then
+		echo "- Latest objects have been fetched from '$ORIGIN'"
+	fi
+	[ "$commit" = "$BRANCH" ] && echo "- Release branch '$BRANCH' has been merged into '$BASE_BRANCH'"
+	if noflag keep; then
+		if [ $localbranchdeleted -eq $FLAGS_TRUE ]; then
+			keepmsg="has been locally deleted"
+		else
+			keepmsg="is still locally available"
+		fi
+		if [ $remotebranchdeleted -eq $FLAGS_TRUE ]; then
+			keepmsg=$keepmsg"; it has been remotely deleted from '$ORIGIN'"
+		elif git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+			keepmsg=$keepmsg"; it is still remotely available on '$ORIGIN'"
+		fi
+	else
+		keepmsg="is still locally available"
+		if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+			keepmsg=$keepmsg"; it is still remotely available on '$ORIGIN'"
+		fi
+	fi
+	echo "- Release branch '$BRANCH' "$keepmsg
+
+	if flag push; then
+		echo "- '$BASE_BRANCH' and tags have been pushed to '$ORIGIN'"
+	fi
+	echo "- You are now on branch '$(git_current_branch)'"
+	echo
+}
